### PR TITLE
REFACTORED CSS AND JS

### PR DESCRIPTION
**Pull request by ananyakushal**

### CODE REVIEW

**Review by arpitghura — COMMENTED** [review]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face: Thanks for giving your time to contribute to <b>Typing Test</b> Project. <br/> You should join our <a href='https://discord.gg/7c3VGDutmS'>Discord</a> chat - we help and encourage each other to contribute to open source little and often

**Comment by arpitghura** [comment]
image
Make the `Practice your typing skills` text center align.

**Comment by ananyakushal** [comment]
I have Center-aligned the subtitle. Please have a look on it.

**Review by arpitghura — APPROVED** [review]
good

**Pull request merged**
