### PR TITLE
Add navbar and footer to practice page

### PR DESCRIPTION
**Pull request by dissyulina**
# Added Navbar and Footer to Practice page - Solve issue #32

## PR Contains:
- Add navbar and footer with the same styling as the homepage.

## Screenshot:
image

### CODE REVIEW

**Comment by dissyulina** [comment]
Hi @arpitghura , should I resolve the conflict myself? Sorry I'm new at this. Thanks.

**Comment by arpitghura** [comment]
Hey, @dissyulina I have resolved the **merge conflict**.

**Comment by arpitghura** [comment]
Thank you @dissyulina for your contribution.

**Comment by dissyulina** [comment]
Thank you @arpitghura :)

**Pull request merged**
