### PR TITLE
fixed Night mode problem #110

### PR DESCRIPTION
**Pull request by Hritambhar**

### CODE REVIEW

**Review by arpitghura — COMMENTED** [review]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face: Thanks for giving your time to contribute to <b>Typing Test</b> Project. <br/> You should join our <a href='https://discord.gg/7c3VGDutmS'>Discord</a> chat - we help and encourage each other to contribute to open source little and often

**Comment by arpitghura** [comment]
What changes you have made; can you please justify them with screenshots?

**Comment by Hritambhar** [comment]
these are the two changes done by me

**Comment by arpitghura** [comment]
Hey, the images are not showing up. One thing you can do is reply with images over GitHub not in emails.

**Comment by Hritambhar** [comment]
Screenshot from 2023-02-09 01-14-24

**Comment by arpitghura** [comment]
What problem does this PR solve?

**Pull request closed without merging**
