### PR TITLE
Updated screenshots in README.md

### PR DESCRIPTION
**Pull request by Tapo41**

### CODE REVIEW

**Review by arpitghura — CHANGES_REQUESTED** [review]
Use `assets\images` folder to upload and fetch images. 
DO NOT USE ANY EXTERNAL 3RD PARTY WEBSITE FOR THIS.

**Comment by Tapo41** [comment]
@arpitghura the  updated images are not present in assets\images folder.. 
So, I have to add updated screenshots there?

**Comment by arpitghura** [comment]
> @arpitghura the updated images are not present in assets\images folder.. So, I have to add updated screenshots there?

Take screenshots of the webpage using `CTRL + SHIFT + S` and add that image in assets\images folder.

**Comment by Tapo41** [comment]
Screenshot_20230212_010240
@arpitghura There is no permission for uploading

**Comment by arpitghura** [comment]
> Screenshot_20230212_010240 @arpitghura There is no permission for uploading

1. Fork the repo in your account
2. Add images to the repo that you forked in your account (`https://github.com/<your_username>/typing-test`) 
3. Put your username at `<your_username>`
4. Now when you add photos to the repo, update the readme file.
5. and create a PR or update changes in this PR.

**Comment by arpitghura** [comment]
Are you working on this PR ?

**Comment by arpitghura** [comment]
Closing this PR as no response is recieved.

**Pull request closed without merging**
