### PR TITLE
added icons in the navbar

### PR DESCRIPTION
**Pull request by TheXro**
#99

### CODE REVIEW

**Review by arpitghura — COMMENTED** [review]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face: Thanks for giving your time to contribute to <b>Typing Test</b> Project. <br/> You should join our <a href='https://discord.gg/7c3VGDutmS'>Discord</a> chat - we help and encourage each other to contribute to open source little and often

**Review by arpitghura — CHANGES_REQUESTED** [review]
Add some transitions on hovering.

**Comment by TheXro** [comment]
> Add some transitions on hovering.

Can you please explain what type of transition should I add

**Comment by arpitghura** [comment]
Add the transition property on hovering like 
`transition: all .2s ease`
Read more about transitions [Here at MDN Docs ](https://developer.mozilla.org/en-US/docs/Web/CSS/transition)

**Review by arpitghura — APPROVED** [review]
looks good

**Pull request merged**
