### PR TITLE
Update Images in readme

### PR DESCRIPTION
**Pull request by Preeti8021**
Issue #88 
The images on the readme file were outdated, so I have updated them with new images. 
I have uploaded the new images and renamed the old images with suffix '_old'. 
I have added the image for the latest feature dark theme, also included the "Code Peak'23" in open source events.

### CODE REVIEW

**Comment by Preeti8021** [comment]
Kindly help me out as there seems to be an issue in Greeting/welcome(pull_request_target), the check failed
Please let me know.

**Comment by arpitghura** [comment]
> Kindly help me out as there seems to be an issue in Greeting/welcome(pull_request_target), the check failed Please let me know. @arpitghura

There is no issue with that. But I am not able to view the images. Don't know why. It is saying `Unable to render rich data`

**Comment by Preeti8021** [comment]
If its still not showing, I have seen some solution on github that by changing the dns it could work. Method 1 in the link.
https://youtu.be/1MMnUBsUczY?si=hR3cc9QT3vWRk5Cx 
Please tell me if it's still showing unable to render.

**Comment by arpitghura** [comment]
> If its still not showing, I have seen some solution on github community that by changing the dns it could work. Method 1 in the link. https://youtu.be/1MMnUBsUczY?si=hR3cc9QT3vWRk5Cx Please tell me if it's still showing unable to render.

Yup, the issue resolved with this step. Thank you.

**Pull request merged**
