### PR TITLE
Created a new UI

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
Created a new UI for Webpage

### CODE REVIEW

**Review by arpitghura — COMMENTED** [review]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face: Thanks for giving your time to contribute to <b>Typing Test</b> Project. <br/> You should join our <a href='https://discord.gg/7c3VGDutmS'>Discord</a> chat - we help and encourage each other to contribute to open source little and often

**Comment by Bharadwajshivam28** [comment]
Review it sir

**Comment by arpitghura** [comment]
The UI is not looking good. If you want to create good UIs. Firstly, go on [dribble.com](https://dribbble.com/?/) and see good single page designs.

**Comment by Bharadwajshivam28** [comment]
ok sir

**Pull request closed without merging**
