### PR TITLE
[Fixes: #134] Placing textbox on screen

### PR DESCRIPTION
**Pull request by sarthakvermaa**
Issue number: #134 
To check the position of the user input text box, I have set a condition of comparing dynamic text box height with 80% of the viewport height. Firstly I have created two text boxes in practice.html, and commented out the previous one. 
Then, I styled them in practice.css. And at last, I added some elements in practice.mjs, and with the condition check I assigned the element to the variable declared in that file.
Hope it helped!

### CODE REVIEW

**Comment by sarthakvermaa** [comment]
@arpitghura Can you please tell why am I not able to do PR?

**Comment by arpitghura** [comment]
The functionality does not persists for `easy` - `2 minutes` session. Look at it.
image

**Comment by sarthakvermaa** [comment]
@arpitghura Well the functionality depends on the text box size. Here, if there are less than 12(>12) lines then only the input box is placed right below the reset button (keeping the condition "Sarthak, you have to make the text box inline that is placed just below the reset button when the dynamic-text-box height is less than 80% of the viewport height and when the height is greater than 80% then the current behavior is already written.The height is less in case of easy and intermediate difficulty and in case of less time sessions and also do check about these." asked in mind). 
If there's any specific change needed I'll look at it.

**Comment by arpitghura** [comment]
LGTM. Merged.

**Pull request merged**
