### PR TITLE
Fixed Issue #110

### PR DESCRIPTION
**Pull request by ihsingh2**

### CODE REVIEW

**Review by arpitghura — COMMENTED** [review]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face: Thanks for giving your time to contribute to <b>Typing Test</b> Project. <br/> You should join our <a href='https://discord.gg/7c3VGDutmS'>Discord</a> chat - we help and encourage each other to contribute to open source little and often

**Comment by ihsingh2** [comment]
Relevant screenshots:

Screenshot from 2023-02-12 23-11-47

Screenshot from 2023-02-12 23-12-17

**Comment by ihsingh2** [comment]
Oops, it seems someone had raised the same issue and was assigned to it.

I am sorry for being ignorant. Also please label this as diversion2k23.

**Comment by arpitghura** [comment]
Hey, remove the commits of changing the history section on profile page. Leave only the theme preference commit and do resolve the merge conflict.

**Comment by arpitghura** [comment]
Are you still working on this PR?

**Review by arpitghura — CHANGES_REQUESTED** [review]
You are not updating the `mode` property in localStorage when the user switches to darkmode. Please do it.

**Review by arpitghura — APPROVED** [review]
Thank you

**Pull request merged**
