### PR TITLE
fixed footer bug

### PR DESCRIPTION
**Pull request by aviiciii**
I have fixed the footer bug metioned above in index.css and is reflected across all the pages.

### CODE REVIEW

**Comment by aviiciii** [comment]
This Pull Request will solve the footer issue https://github.com/arpitghura/typing-test/issues/51

**Comment by arpitghura** [comment]
Could you please add the screenshots of the webpage before and after the changes?

**Comment by aviiciii** [comment]
Footer starts at **bottom of content** before changes and footer starts at the **bottom of the page** after changes. Kindly refer the images attached below.

### Before changes:
**1.**
image

**2.**
image

### After changes:
**1.**
image

**2.**
image

**Comment by aviiciii** [comment]
### Before:
image

### After:
image

**Comment by Shantanu-Meta** [comment]
hey @aviiciii , i have a problem. why my pull request is not accepted . it is showing error in greeting/greeting run-action first interaction error. can you please help me to figure it out ?

**Comment by arpitghura** [comment]
> hey @aviiciii , i have a problem. why my pull request is not accepted . it is showing error in greeting/greeting run-action first interaction error. can you please help me to figure it out ?

Hey @Shantanu-Meta just pull the changes in your repository. I have made some changes online.

**Comment by Shantanu-Meta** [comment]
okay i have done it. @arpitghura . can you please check it out ?

**Comment by aviiciii** [comment]
@arpitghura kindly check the above screenshots and accept the pull request if no changes are required

**Comment by arpitghura** [comment]
Thanks @aviiciii for contributing to the project, looking forward to having more contributions from your side.

**Pull request merged**
